### ISSUE TITLE
Database issue?

### ISSUE THREAD

**Issue by SalehCoder** [vimodev/dronemap#1]
Hi

I would love to get this amazing project working. However, whenever I click 'Synchronize Database' in the UI, I get the following error message on the docker logs:

`
Starting database file sync
{"level":50,"time":1639565577215,"pid":19,"hostname":"9850ca5e87f5","name":"dronemap-backend","msg":"insert into `files` (`created_at`, `file_path`, `id`, `sha256`, `size`, `updated_at`) values ('2021-12-15 13:52:51', '/Drone Backup/DJI Mavic 2/2020-04-24/DJI_0528.MP4', 'efb7890c-c214-4afa-b44f-e85ebf2b31e8', '329ecbf5fd94c706dd0954375816618230e862cc47b77671ab00743ccdc8a2e0', 3758910266, '2021-12-15 13:52:53') - ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'size' at row 1"},
Starting database file sync
`

Nothing happens on the web UI. The drone data doesn't get populated on the map. However, that error shows that it might be an issue with the database with the column 'size' being populated with out of range data.

Here's my docker-compose implementation:
`
services:
  dronemap:
    image: vimodev/dronemap:latest
    ports:
      - "3333:3333"
    restart: unless-stopped
    environment:
      - DB_CONNECTION=mysql
      - MYSQL_HOST=dronemap_database
      - MYSQL_PORT=3306
      - MYSQL_USER=dronemap
      - MYSQL_PASSWORD=2024cad0b930c
      - MYSQL_DB_NAME=dronemap
      - TZ=Asia/Kuwait
    volumes:
      - dronemap_nfs_volume:/footage:ro
    depends_on:
      - dronemap_database
    networks:
      - dronemap-network

  dronemap_database:
    image: mariadb:10
    environment:
      - MYSQL_DATABASE=dronemap
      - MYSQL_USER=dronemap
      - MYSQL_PASSWORD=2024cad0b930c
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - TZ=Asia/Kuwait
    networks:
       - dronemap-network
    ports:
      - "3306:3306"
    restart: unless-stopped

networks:
    dronemap-network:
      driver: bridge
      enable_ipv6: false
      ipam:
        driver: default
        config:
          - subnet: 10.10.10.0/24
          
volumes:
  dronemap_nfs_volume:
    driver_opts:
      type: "nfs"
      o: "addr=ds1819.*******.com,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/volume1/Files/Drone"
`

Thank you.

**Comment by vimodev** [comment]
I have changed a simple database data type to allow for larger file sizes (417506b5c9fedba727fcf9417125ca9de84716bf)
I have been unable to test it since I do not have a DJI footage file as large as this at hand.
It's also live on docker hub.
